### ISSUE TITLE
[QUESTION] site problem

### ISSUE THREAD

**Issue by gregorst3** [PawlicaWeb/CryptoPonzi#11]
Hi, have i to download bitcoin core to use this script?

**Comment by PawlicaWeb** [comment]
You need bitcoind to use this script.
https://github.com/bitcoin/bitcoin/

**Comment by gregorst3** [comment]
Thanks. After that i had installet it. Have i to do other things?

**Comment by gregorst3** [comment]
And can i use electrum instead of bitcoind?

**Comment by gregorst3** [comment]
Done bitcoind now have i to import my wallet in bitcoin core?
